### ISSUE TITLE
Turbo lift floating in space

### ISSUE THREAD

**Issue by Medea85** [dapperrobotbear/Stage9#151] opened 2017-12-02 17:38 UTC
If you spawn a Turbo lift or a shuttle in the Main Shuttle Bay, then fly out and activate a remote saucer separation, the previously spawned lift and shuttle remain in place as the saucer files away, leaving them floating in space.

You can even to an emergency transport to the lift.
![turbo lift in space](https://user-images.githubusercontent.com/34193076/33518109-7fa1cea4-d787-11e7-8b5c-aef0c3680981.png)

**Comment by OssiBRI** [comment] 2017-12-08 19:10
There's also a red blinking position light floating between drive section and the turbo capsule.

**Comment by Gary-Baggins** [comment] 2018-03-15 00:50
@TheStrato @HPringles this is a duplicate of one i confirmed earlier and goes into more detail, recommend closing this one.

**Comment by TheStrato** [comment] 2018-03-15 00:52
Less descriptive duplicate. Closing ticket.

**Closed by TheStrato** 2018-03-15 00:52 UTC
