### ISSUE TITLE
V0010-QA3 Deck 1 Bridge Exterior Appearing in Interior

### ISSUE THREAD

**Issue by pedrozote** [dapperrobotbear/Stage9#376] opened 2018-03-15 01:33 UTC
PC - Windows 10
Deck 1 - Bridge
When you select in the tactical menu the nacelle view and then you go to the helm in 3rd person, leave the post, the exterior part of the ship will be visible in the interior and also will be solid, making it impossible to do any action, the only solution is to restart the game.

Steps.
1- Go to the tactical menu and select Viewscreen Nacelle View 
![1](https://user-images.githubusercontent.com/37256459/37439422-d4a271b6-27d6-11e8-8e2c-bf57580bb33f.png)
2- Sit at the helm and fly the ship in 3rd person view
![2](https://user-images.githubusercontent.com/37256459/37439472-07e884e8-27d7-11e8-8f59-ec804a143479.png)
![3](https://user-images.githubusercontent.com/37256459/37439483-15364bee-27d7-11e8-9745-643706addeb1.png)
3- Leave the helm without going back to first person mode.
![4](https://user-images.githubusercontent.com/37256459/37439532-4bba2da2-27d7-11e8-8d5e-568bfdc9b6f2.png)
![5](https://user-images.githubusercontent.com/37256459/37439549-5b694bde-27d7-11e8-9453-8e3c68360c2a.png)
4- You won't be able do pass through the exterior.

**Comment by TheStrato** [comment] 2018-03-15 03:48
Duplicate of issue in #303. Closing this ticket.

**Closed by TheStrato** 2018-03-15 03:48 UTC
