### ISSUE TITLE
V0010-QA2 - Laying phaser on floor of shuttle weighs down Shuttle

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#352] opened 2018-03-14 01:31 UTC
**Summary**

Basically if I bring a phaser on board a shuttlecraft then drop it and try to fly, it's as if its Weighed down

***What is the expected correct behavior?***

I should be able to bring the phaser with me to fly around space

**Steps to reproduce**

1. Take a Phaser
2. Bring it on Shuttle
3. Drop it
4. Try to take off

**Relevant logs and/or screenshots**

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

**Possible fixes**

**Comment by nkjellman** [comment] 2018-03-14 02:33
This is probably related to the player and NPC's being able to push shuttles around. 

The issue is, things in Stage 9 don't have any mass simulation. Every dynamic object behaves like it weighs the same.

**Comment by scragnog** [comment] 2018-03-14 16:39
confirmed, but this won't be fixed for V10. We should be able to get this working in V11. For now, just don't bring your weapons with you on shuttles :-)

**Comment by TheStrato** [comment] 2018-03-16 19:32
NaB. Closing ticket.

**Closed by TheStrato** 2018-03-16 19:32 UTC
