### ISSUE TITLE
Main Shuttlebay - Mis-spelt above door: Caution Variable Gravity AI

### ISSUE THREAD

**Issue by tuvok2018** [dapperrobotbear/Stage9#422] opened 2018-03-19 22:37 UTC
<!--- ^^ PLEASE SET THE TITLE TO FOLLOW THIS STYLE
          V0.0.10 - Deck 4 - Main Shuttlebay - Mis-spelt above door: Caution Variable Gravity AI
          If you goto the bell and turn around and look at the staircase opposite it is above the door to the left of there.

Discord Name(If Applicable):   
CPU:  Ryzen 1800X
GPU:  Nvidia 1080ti
Operating System:  Windows 10 

***What is the expected correct behavior?***

Correct spelling

![caution variable gravity ai](https://user-images.githubusercontent.com/36381392/37625920-d546fa7c-2bc5-11e8-8120-4f15b2f5e82e.jpg)

**Comment by jeppelykke** [comment] 2018-03-20 18:37
![stage9 screenshot 2018 03 20 - 19 37 26 71](https://user-images.githubusercontent.com/33987322/37675691-2f491f54-2c76-11e8-8da9-ab05c47a8ba5.png)

**Comment by tenko23** [comment] 2018-03-24 07:47
Confirmed on a Mac also.  Looking up close, it looks like an adjacent panel has covered it up. 
 @TheStrato , if you would, please add Mac to the list.

![screen shot 2018-03-24 at 2 44 15 am](https://user-images.githubusercontent.com/34230416/37861717-93393c58-2f0d-11e8-84a6-07184d30b615.jpg)
![screen shot 2018-03-24 at 2 44 46 am](https://user-images.githubusercontent.com/34230416/37861718-99afb968-2f0d-11e8-9318-521189486090.jpg)

**Comment by jeppelykke** [comment] 2018-04-01 15:01
@HPringles Transferred to Bugz

**Closed** 2018-04-01 21:17 UTC
Labels: Mac, Rooms, Windows
