### ISSUE TITLE
Win - V0010-QA1 - Deck 08 Turbolift issues! random throw out 

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#228] opened 2018-03-11 12:29 UTC
**Summary**
Been trying to pin point how this bug accrues but it seems to be random :o 
Enter the Deck 08 turbolift (Port or Starboard) and take the turbolift to Either the Port or Starboard. most times nothing happen other times you get throw out into the corridor behind the force field so you stuck. Other times you thrown into space. 

***What is the expected correct behavior?***
Turbolift takes you from Port to Starboard
Turbolift takes you from Starboad to Port.

**Steps to reproduce**
1. Enter turbolift on Deck 08
2. Go to Port or Starboard. 

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 11 - 13 13 19 37](https://user-images.githubusercontent.com/33987322/37253287-1be56438-2530-11e8-8bbc-cea68af77476.png)
![stage9 screenshot 2018 03 11 - 13 12 37 14](https://user-images.githubusercontent.com/33987322/37253289-1daf6822-2530-11e8-9296-eb8867bf775d.png)
![stage9 screenshot 2018 03 11 - 13 13 20 83](https://user-images.githubusercontent.com/33987322/37253291-1fd9e726-2530-11e8-9142-ea43f866a30c.png)

**Possible fixes**
Revisit Deck08 in UE.  Seems to not be completely done! :)

**Comment by HPringles** [comment] 2018-03-11 20:14
# Confirmed Issue

**Comment by dapperrobotbear** [comment] 2018-03-12 07:41
Please reconfirm in QA2

**Comment by dapperrobotbear** [comment] 2018-03-12 09:20
@metaphim428 Can you try to diagnose this?

**Comment by dapperrobotbear** [comment] 2018-03-18 03:50
Figured out what this was. Please confirm in >QA4

**Comment by EazyCheeze1978** [comment] 2018-03-18 12:13
Unfortunately not fixed... When testing the 'lift just now I found this: Starboard back to Port works as intended, but Port to Starboard throws me out. Traveling from the Battle Bridge back to Picard's Starboard doesn't throw me out. Traveling from a higher deck (7, the Arboretum in my test case) to 8's Starboard doesn't throw me out. Traveling from a lower deck (9, the Stellar Cartography corridor in my test case) to 8's Starboard also doesn't throw me out.

**Comment by jeppelykke** [comment] 2018-03-18 12:13
Still issue in V0010-GM1 with: **Deck 08 Captain Quarters | Port** if you try to take turbolift off this deck you get kicked out into space.

**Comment by dapperrobotbear** [comment] 2018-03-19 03:47
Tried again to fix this. Reconfirm in >GM1

**Comment by jeppelykke** [comment] 2018-03-20 18:20
@TheStrato  Confirmed Fixed for windows (V0010 HF1)

**Comment by MrPeppow** [comment] 2018-03-20 22:17
Can confirm Fix on Linux HF1

**Comment by TheStrato** [comment] 2018-03-21 09:25
Resolved. Closing this ticket.

**Closed by TheStrato** 2018-03-21 09:25 UTC
