### ISSUE TITLE
Win - V0010-QA2 - Crew rooms (Worf and Data) replicators malfunction.

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#289] opened 2018-03-12 17:43 UTC
**Summary**
Lt. CMD Worf called Engineer to report to his room Deck 02 | 6214 that his replicator is malfunction.  a diagnoses of the problem was lack of power to all crew replicator on that floor.

***What is the expected correct behavior?***
To order a cup of Tea Earl Grey Hot from the replicator.

**Steps to reproduce**
1. Go to Lt. Cmd. Worf room Deck 02 | 6214
2. Go to Lt. Cmd. Data room Deck 02 | 4553
3. try use replicators.

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 12 - 18 36 27 67](https://user-images.githubusercontent.com/33987322/37299966-1500b870-2625-11e8-98fe-ad48e33481f1.png)

**Possible fixes**
Turn on the power to the replicators.

**Comment by jeppelykke** [comment] 2018-03-12 18:04
@TheStrato sorry this was reported....

Win-V0010-QA1 - Worfs Quarters - Unconnected Replicator #246

I missed it.. sorry for double post

**Comment by TheStrato** [comment] 2018-03-12 18:16
Self reported duplicate of #246. Closing this ticket.

**Closed by TheStrato** 2018-03-12 18:16 UTC
Labels: duplicate
