### ISSUE TITLE
V0010-QA3 -  Main bridge Lighting issue

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#391] opened 2018-03-15 16:33 UTC
**Summary**

Potentially related to #372 , but between QA2 and QA3 the lighting changes to the exterior views of the ship result in very bright illumination on exterior surfaces, which after a few full seconds drops to the appropriate calculated lighting levels/shadows.

***What is the expected correct behavior?***

Lighting as in QA2 and previous, where lighting on exterior (of the ship) surfaces faster?/differently?

**Steps to reproduce**

Primary Steps:
1.Travel to main bridge, look immediately out the main viewer.
2.Observe lighting on planet and station as full brightness, then after delay, switch to normal lighting

Alternate Steps 1:
1. on main bridge, switch main viewer to alternate view (such as saucer visible view)
2. look immediately through the view screen at the surface of the enterprise
3. observe full brightness, without shadow, then a few seconds later, normal lighting and shadow.

Alternate Steps 2:
1. Travel to Ready Room
2. look immediately out the porthole next to the captain's desk
3. observe extreme brightness, without shadow
4. approach the window, the lighting will change
5. this one doesn't fully resolve itself.  Still ends up looking worse than QA2.

**Relevant logs and/or screenshots**

Bridge Lighting Example:
![screen shot 2018-03-14 at 11 07 53 pm](https://user-images.githubusercontent.com/35311046/37476950-d632e4d6-284c-11e8-8e0b-ffcc218b5024.png)
![screen shot 2018-03-14 at 11 07 56 pm](https://user-images.githubusercontent.com/35311046/37476957-d8e15230-284c-11e8-8c3f-55988534998c.png)

Bridge Lighting Example 2:
![screen shot 2018-03-14 at 11 05 42 pm](https://user-images.githubusercontent.com/35311046/37477091-2ef6ad32-284d-11e8-8859-a9edb614c3bc.png)
![screen shot 2018-03-14 at 11 05 46 pm](https://user-images.githubusercontent.com/35311046/37477095-3108af8a-284d-11e8-82c5-fbb2754ec881.png)

Ready Room Example:
![screen shot 2018-03-14 at 11 05 57 pm](https://user-images.githubusercontent.com/35311046/37476998-fa8449ec-284c-11e8-82f8-405b09d73015.png)
![screen shot 2018-03-14 at 11 06 10 pm](https://user-images.githubusercontent.com/35311046/37477005-fdcaa68c-284c-11e8-97f4-82cc5f9813af.png)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by scragnog** [comment] 2018-03-15 17:41
myyyyyyyyyyyyyyyyyyy bad. I made a screw up. The less said about it the better. All fixed now :-D

**Comment by Sciencekeeper** [comment] 2018-03-17 09:30
@TheStrato can't reproduce anymore in QA4Win seems fixed

**Comment by TheStrato** [comment] 2018-03-17 09:31
Resolved. Closing ticket.

**Closed by TheStrato** 2018-03-17 09:31 UTC
