### ISSUE TITLE
Mac - V0010-QA1 - Ready Room Shadow error/load error

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#268] opened 2018-03-12 01:29 UTC
**Summary**

When looking out the Ready Room window onto the hull, the player shadow is obstructed by some thing initially, then is no longer obstructed.

***What is the expected correct behavior?***

Approaching the window should display a smooth transition of your shadow appearing and walking toward the window (cast as a shadow on the hull)

**Steps to reproduce**

1.Travel to the Bridge
2.Enter the Ready Room
3.Observe the dark area in shadow to the left of the window on the hull outside
4. Walk closer (past the desk)
5. Observe the large shadow disappear, leaving your player shadow in view suddenly.

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 10 44 41 pm](https://user-images.githubusercontent.com/35311046/37261461-0fa5263e-2573-11e8-96f9-c596142daeb0.png)

![screen shot 2018-03-10 at 10 44 49 pm](https://user-images.githubusercontent.com/35311046/37261468-1caab2e0-2573-11e8-8c31-3276658ba1a6.png)

**Possible fixes**

This seems like an issue with a load taking place when you approach the window, something is obstructing the light initially, but that object disappears or moves when you get closer.

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by dapperrobotbear** [comment] 2018-03-12 02:13
I'm pretty sure this is caused by the new way we're doing light blocking. @scragnog will need to fix that.

**Comment by jgbr** [comment] 2018-03-12 15:46
Somewhat better in QA2

**Comment by dapperrobotbear** [comment] 2018-03-12 21:15
Really? Hmmm, I didn't change anything in this regard. It might be related to which space location you are at and your angle to the sun.

**Comment by JonathanNStewart** [comment] 2018-03-13 02:35
An additional, and possibly related, issue is that the wall right of the window isn't blocking light. The wall is between Picard and his shadow on the hull. You can't see the shadow if you're standing where Picard is.

**Comment by jeppelykke** [comment] 2018-04-01 18:05
@HPringles Transferred to Bugz

**Comment by jeppelykke** [comment] 2018-04-01 18:11
@HPringles Transferred to Bugz

**Closed** 2018-04-01 20:35 UTC
Labels: Moved Internal
