### ISSUE TITLE
V0010-QA3 Deck 13: Shuttlebay 2 Labels come off Antigrav cart

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#381] opened 2018-03-15 03:36 UTC
Summary
Shooting the antigrav cart in Shuttlebay 2 causes the labels to fly off.

Desired Result
Labels stay stuck on their surface.

Reproducible Steps:
1. Pick up phaser rifle off of antigrav cart.
2. Shoot up antigrav cart.
3. Labels fall on floor

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37443135-89fadcc0-27e0-11e8-8336-be92c15891ca.png)

**Comment by TheStrato** [comment] 2018-03-15 03:45
Duplicate of the issues mentioned in #350 Closing this ticket.

**Closed by TheStrato** 2018-03-15 03:45 UTC
