### ISSUE TITLE
Win - V0010-QA1 Replicators

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#191] opened 2018-03-11 01:36 UTC
All replicators. You can click the replicator button continuously. This causes the animation to slow down and stay on. It will still allow the item to come in. But the sparkle pattern says on.

What it should do

Replicator creates one item. Cannot press button intill item is removed.

Steps to reproduce

Rapidly press the button to keep spawning items.

![image](https://user-images.githubusercontent.com/5162659/37248527-b210634c-24a2-11e8-888e-69a7c6f4ff83.png)

**Comment by HPringles** [comment] 2018-03-11 20:27
# Unconfirmed Issue

***I cannot reproduce myself***

**Comment by Gary-Baggins** [comment] 2018-03-15 01:09
I can reproduce this to an extent but only if i constantly spam the panel for about 10 seconds and it really depends on whether you end on "produce beverage" or "recycle" which the latter would leave the dispensing tray empty, tag windows just because @TheStrato @HPringles

**Comment by HPringles** [comment] 2018-03-17 13:58
# Replicators are a proof of concent - NaB

**Comment by TheStrato** [comment] 2018-03-17 20:49
Replicators are still a WIP. Closing this ticket.

**Closed by TheStrato** 2018-03-17 20:49 UTC
