### ISSUE TITLE
V0010 (Win) - All decks/rooms - First person camera issues

### ISSUE THREAD

**Issue by digitalmagick** [dapperrobotbear/Stage9#421] opened 2018-03-19 19:35 UTC
**Basic Info**
Discord Name(If Applicable):   DigitalMagick#9707
CPU:  Intel Core i7 6700 
GPU:  NVIDIA GeForce GTX 1080 Ti (ROG STRIX)
Operating System:   Windows 10 Pro
Peripherals: Oculus Rift (Not used in Windows version test)

**Summary**
Camera position is awkward when pressing Z in first person.
- The camera appears to be a short ways ahead of the character.  (Only a matter of inches.  While this is minor it still feels awkward)
- (Problem A) When turning past a certain point, the character mesh will hit it's neck-limit, and re-position itself, altering the position (rather than merely direction) of the player's viewpoint.  This can be especially jarring when unexpected.
- (Problem B) If reversing directions, this can also cause the player to jut aside of the intended direction for a moment.  (ie. strafe left for a few feet, then right, you bob forward or back for a moment while the invisible mesh turns around)

***What is the expected correct behavior?***
When in first person, normally the camera behaves as if it is attached to the character's eyes (or an inch in front of) however pressing Z is intended to detach and correct this behavior for a traditional first person interface, where the camera tracks smoothly along at roughly eye-level, and pivots direction in-place.
- If the player is not moving, turning the camera should not cause the viewpoint position (X,Y,Z) to change, only the view-angle (rotation/direction).

**Steps to reproduce**
1. Begin a game in first person.  (or press V to switch to 1st person if already in 3rd)
2. Press Z to disable head-bob.
3. Observe camera relocation.
4. Move forward, observe successful lack of head-bob.
5. Turn slowly (with mouse) until you notice the camera position suddenly change as the character re-positions. (Problem A)
6. Strafe a few feet to one side, stop, then strafe in the opposite direction.  Observe camera moves forward/back when only sideways motion was involved. (Problem B)

**Comment by kaadaq** [comment] 2018-03-22 18:13
Performed Steps 1-4.  Camera relocation is confirmed -- the view changes between head bob and no head bob.    That part is validated.

I did not get a camera position "jump" when rotating in place.   I also do not have issues with the camera adjusting forward to back when strafing.   Unable to validate that.

@HPringles, review for action.

**Comment by TheStrato** [comment] 2018-03-23 23:32
Working as intended for now. More improvements are planned in the future. Closing this ticket.

**Closed by TheStrato** 2018-03-23 23:32 UTC
