### ISSUE TITLE
V0010-QA2 Main Shuttlebay Bell does not Chime

### ISSUE THREAD

**Issue by kaadaq** [dapperrobotbear/Stage9#312] opened 2018-03-13 01:04 UTC
Summary
Ship's bell does not chime.   Looks like the clapper/knocker is missing.

Expected performance
CLANG!

Reproducible Steps
1. Press enter on ship's bell
2. Move it back and forth

Screenshot:
![image](https://user-images.githubusercontent.com/34050343/37317014-e26360f2-2638-11e8-8852-8b1a97a001ad.png)

**Comment by Gary-Baggins** [comment] 2018-03-13 14:16
Confirmed.

**Comment by HPringles** [comment] 2018-03-13 14:32
I was able to make this work - will retest to night

**Comment by Jaredsfs1** [comment] 2018-03-13 16:01
This functions on Mac fine, but does get a little crazy on the physics movement depending on how you move it.

**Comment by TheStrato** [comment] 2018-03-14 20:20
Reported as intermittent, possibly due to OE. Closing this ticket.

**Closed by TheStrato** 2018-03-14 20:20 UTC
