### ISSUE TITLE
Runabout textures showing low res at close range

### ISSUE THREAD

**Issue by Fleet-Admiral-Harrison** [dapperrobotbear/Stage9#448] opened 2018-03-21 20:09 UTC
**Basic Info**

Discord Name(If Applicable):   Fleet Admiral Harrison#9121
CPU:  AMD FX 6300 Black Edition
GPU:  Gigabyte GeForce GTX 950
Operating System:   Windows 10 Pro x64

**Summary**
After fresh install, I went to the main shuttlebay to check out the shuttles, and fly around in the runabout, and I noticed that textures around the ship name weren't going to a higher resolution, as I approached.

***What is the expected correct behavior?***

I should see the textures go to high res as soon as I get near the runabout.

**Steps to reproduce**

1. Go to main shuttlebay
2. Go to runabout, textures stay low res
3.

**Relevant screenshots**

![desktop screenshot 2018 03 21 - 14 59 29 68](https://user-images.githubusercontent.com/37636397/37734608-167e8da4-2d22-11e8-8051-a6dc677bcaba.png)
![desktop screenshot 2018 03 21 - 16 06 38 02](https://user-images.githubusercontent.com/37636397/37734609-168f2f2e-2d22-11e8-9de1-8d2038130538.png)

**Comment by Jaredsfs1** [comment] 2018-03-21 20:39
This is confirmed as an issue on Mac too; but seems to be a problem with the dynamic texture resolution based on distance.  There is a higher res texture that loads, but it only appears if the runabout spawns farther away from you and you approach it.  If you take a turbo to Shuttlebay 1 that is closer to the runabout, the texture looks bad (like above), but if you take a turbo that's further from the runabout and walk all the way to it, it looks like this:

![screen shot 2018-03-21 at 4 00 33 pm](https://user-images.githubusercontent.com/35311046/37736095-5820e514-2d26-11e8-8b82-1488fdf04596.png)

Nitpick* the higher-res texture is still lower resolution than that of the other shuttles in the bay...

**Comment by Gary-Baggins** [comment] 2018-03-23 12:12
Confirmed on V10HF1, please tag graphics @TheStrato @HPringles

**Comment by jeppelykke** [comment] 2018-03-29 14:08
@TheStrato moved!

**Comment by jeppelykke** [comment] 2018-04-01 15:53
@HPringles Transferred to Bugz

**Closed** 2018-04-01 16:02 UTC
Labels: Moved Internal
