### ISSUE TITLE
V0010-GM - Deck 12 to Desk 4 or 3 any destination throws you out of Turbolift

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#409] opened 2018-03-18 16:32 UTC
**Basic Info**

Discord Name(If Applicable):   
CPU:  Core i17
GPU:  Nvidia GTX970(m)
Operating System:   Windows 10 b1709

**Summary**
When trying to go to Deck 4 or 3 from Holodecks or Sick, I get thrown out of the Turbolift every time

***What is the expected correct behavior?***

Arrive safely to Deck 12

**Steps to reproduce**

1. Go to Deck 12| Holodecks
2. Select a Deck 4 or 3 Destination
3. You should get stuck if going to Deck 3 or fall out if going to Deck 4

**Relevant screenshots**

Note:  Going to Deck 12 from 3 or 4 is working normally, so it's only 12 to 3 or 4 that's the issue

**Comment by kaadaq** [comment] 2018-03-18 21:19
Seems to be intermittent.   I tried to reproduce following above steps.   First time, TL seemed to stop (light solid) and I walked toward the door and fell onto the deck beyond the finished area.   Second attempt, I waited, and arrived safely.

Seems like there's the potential to "fall out" if you're moving around.   But it's not automatic.

@HPringles, please review for next steps!

**Comment by cheveffect09** [comment] 2018-03-19 02:17
I can confirm that travling via deck 12 holodeck destination to any where on Deck 3 gets you thrown out each time I tried to replicate it it did this.

**Comment by dapperrobotbear** [comment] 2018-03-19 03:27
Please reconfirm in >GM1

**Comment by MrPeppow** [comment] 2018-03-20 13:01
Can't reproduce on Linux HF1. Seems Fixed. @HPringles @TheStrato

**Comment by tenko23** [comment] 2018-03-20 23:39
Doesn't happen on a Mac, either ;o ~

**Comment by TheStrato** [comment] 2018-03-21 09:28
Resolved. Closing this ticket.

**Closed by TheStrato** 2018-03-21 09:28 UTC
