### ISSUE TITLE
Main Engineering - panel slots not lighting up at red alert...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#426] opened 2018-03-20 06:01 UTC
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**

The four panel slots seen on the one bulkhead in Main Engineering (circled in red in the first screen shot... the four slots on the right - not the two, little round slots on the left within the circle *sorry*) do not light up at red alert.  Attached is a (brief) screenshot from season 4, as a confirmation that they do light.

***What is the expected correct behavior?***

Probably should light up.

**Steps to reproduce**

1.  Go into Main Engineering.
2.  Go to red alert.
3.  Look for the one bulkhead - the bulkhead on the right, when facing the warp core from the back of Main Engineering.  You will find them, you will see that they do not light.

**Relevant screenshots**

![screen shot 2018-03-20 at 12 24 01 am copy](https://user-images.githubusercontent.com/34230416/37637595-9dd9791e-2bd6-11e8-9fa3-ae18dcbc30d8.jpg)
![screen shot 2018-03-20 at 12 31 28 am](https://user-images.githubusercontent.com/34230416/37637597-a1f69fcc-2bd6-11e8-8654-536950ebb64f.jpg)

Thanks!

**Comment by OssiBRI** [comment] 2018-03-20 10:46
https://github.com/dapperrobotbear/Stage9/issues/163

**Comment by Gary-Baggins** [comment] 2018-03-21 12:21
This is a duplicate of #163 which goes into more detail, please tag duplicate and close @TheStrato @HPringles

**Comment by TheStrato** [comment] 2018-03-21 12:46
Duplicate of another ticket that has more detail. Closing this ticket.

**Closed by TheStrato** 2018-03-21 12:46 UTC
