### ISSUE TITLE
V0010-QA2 - Main bridge view screen state not persistent

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#337] opened 2018-03-13 17:01 UTC
**Summary**

When you leave the bridge, the bridge view screen resets to the original view.  

***What is the expected correct behavior?***

The selected main view should be preserved or persistent (perhaps the saucer section visible view should be the default for now due to the mesh failing to load in third person bug anyway).  It's especially annoying when setting a warp location, wandering about the first deck, (or elsewhere) and returning.  

**Steps to reproduce**

1.Travel to the bridge
2.Set a viewscreen view other than the default from the tactical station
3.leave the bridge (to the ready room for instance, or observation lounge)
4. return to the bridge
5. observe the view screen has reset to it's default view

**Relevant logs and/or screenshots**

![screen shot 2018-03-12 at 9 12 17 pm](https://user-images.githubusercontent.com/35311046/37357337-8b848672-26be-11e8-8634-aa48862e18f9.png)
_(Just picked up a 'cuppa' on the way to Veridian and, where did the saucer go?)_

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jgbr** [comment] 2018-03-13 17:21
I can confirm this on Mac. It seems to be related to how far away you go from the view.

In my case I chose saucer view and went to ready room and came back, it was still on saucer view.

I went to the observation lounge and it had reset to the default view. 

@HPringles Mac , needs windows check

**Comment by scragnog** [comment] 2018-03-14 17:26
confirmed, but due to the way our dynamic room loading works, this is a lot more complicated than it sounds. Rooms 'reset' when unloading and reloading. We have some ideas in-place to make things more persistent, but not for v10.

**Comment by TheStrato** [comment] 2018-03-16 19:30
NaB. Closing ticket.

**Closed by TheStrato** 2018-03-16 19:30 UTC
