### ISSUE TITLE
Win - V0010-QA4 - Deck 08 Broken turbo lift Captains Q. Port & Starboard and invisible wall on deck 08

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#398] opened 2018-03-17 08:59 UTC
**Summary**
As soon as you transport on board the ship and heads to turbo lift and try to take the turbo lift to Deck 08 Captain's Quarters Port & Starboard, the turbo lift comes to the location but does not open the door. 

***What is the expected correct behavior?***
As soon as you arrive on Deck 08 the turbo lift doors opens.

**Steps to reproduce - DOOR DON'T OPEN**
1. Launch the game
2. Go into Tubolift 
3. Head down to Deck 08 Captain's Quarters Port  or Starboard... 

**Steps to reproduce - Invisible Wall**
1. Launch the game
2. Go into Tubolift 
3. Head down to Battlebridge
4. Head from battlebridge to Deck 08 Captain's Quarters Port  or Starboard... 
5. Head down towards Captain Picards Quarters. 
_6. Try take turbolift off Deck 08 and you get kicked out into space._

**Relevant logs and/or screenshots**
![stage9 screenshot 2018 03 17 - 09 56 55 71](https://user-images.githubusercontent.com/33987322/37553484-8efee24e-29c9-11e8-95e2-1efb7961c965.png)

**Comment by dapperrobotbear** [comment] 2018-03-18 04:31
Please confirm in >QA4

**Comment by EazyCheeze1978** [comment] 2018-03-18 11:19
@TheStrato Looks like the Door Doesn't Open part is confirmed fixed, and... the Invisible Wall doesn't happen nor does Step 6 happen either. Great stuff!

**Comment by TheStrato** [comment] 2018-03-18 11:20
Resolved. Closing the ticket.

**Closed by TheStrato** 2018-03-18 11:20 UTC
