### ISSUE TITLE
Win - V0010-QA1 - Changing key binds makes it so you can't open warp drive menu/open shuttle door

### ISSUE THREAD

**Issue by nkjellman** [dapperrobotbear/Stage9#202] opened 2018-03-11 03:01 UTC
**Summary**
Some functions do not respond to key bind changes.

The button to open the shuttle doesn't work when you click on it. In previous builds, this feature was permanently locked to the left mouse button. I set up my keys so I can use a controller.

When you try to open the warp menu, nothing happens. I tried pressing every button on the console, using every button on my controller, mouse and keyboard. It should be the use button, which is left click. The interact button makes you get up.

***What is the expected correct behavior?***
When you click the use button, it should open the menu/shuttle door, regardless of what key it is mapped to.

**Steps to reproduce**
1. Change the key binds to something else. Perhaps you use an Xbox controller and want to make those buttons work.

Shuttle door:
2. Point at the button to open the hatch.
3. Press the use button and nothing happens. (in v009 and older, this was locked to LMB)

Warp drive:
2. Sit in the helm chair.
3. Hold down the the look around key and look at the Warp Systems button.
4. Press the use button and nothing happens.

**Relevant logs and/or screenshots**
![2018-03-10 2](https://user-images.githubusercontent.com/29221029/37249085-eeada050-24a5-11e8-9b1e-6cd0bfb49756.png)

**Possible fixes**
It looks to me that the key binds for these features are ether hard coded somewhere or aren't directly linked to the Use button. This could be a C++ pointer issue, or it could be another bug in the code.

EDIT: It definitely is something with mapping keys. I deleted my config file and it works. However, when I remapped my keys it stopped working. I changed None to RT (Xbox controller). There is definitely some sort of corruption occurring here. Even resetting it doesn't work. Its almost like you have it set up as a separate key bind.

EDIT: So I have discovered, just simply changing any of the key binds causes an issue.

**Comment by HPringles** [comment] 2018-03-11 17:41
# Confirmed Issue

***Further testing***

This issue also affects the warp core breach panel. Using a newly attached keybind will not work on this. The click, however, does still work.

**Comment by dapperrobotbear** [comment] 2018-03-11 23:24
This is a larger issue with how we handle key bindings. Might not be able to quickly solve this one with how we use OnClick in a LOT of places. Will look into it.

**Comment by scragnog** [comment] 2018-03-14 17:17
yeah this is because we're using 'onclicked' for a ton of stuff, and we can't change the onclicked trigger key/button.  The 'Use' event itself is used in other places, and will remap as expected.
Essentially, we need to go through everywhere we're using 'onclicked' and change it to a different system. Entirely possible, but not enough time for v10.

**Comment by jeppelykke** [comment] 2018-04-01 19:20
@HPringles Transferred to Bugz

**Closed** 2018-04-01 21:20 UTC
Labels: Bug, Linux, Mac, Windows
