### ISSUE TITLE
Mac - V0010-QA1 - Deck 4 - Main Shuttlebay -- Sun glare on deckplate when facing the star

### ISSUE THREAD

**Issue by mikebarber1** [dapperrobotbear/Stage9#239] opened 2018-03-11 15:48 UTC
Go to the main shuttle bay and when you're facing the direction of the star there will be a very bright glare / sun streak on the deck plating. the walls in the shuttlebay aren't transparent so there should be no sunlight to glare against anything except if the door were open and the star visible thru the open door.

I was able to clip thru a part of the wall and verify it was the star light I was seeing
![2018-03-11 11 42 19](https://user-images.githubusercontent.com/25273387/37255374-072d6d46-2522-11e8-8e98-e4b53e7d5ef5.jpg)
![2018-03-11 11 42 28](https://user-images.githubusercontent.com/25273387/37255376-0f99dae6-2522-11e8-8a42-e47b6667f400.jpg)
![2018-03-11 11 42 40](https://user-images.githubusercontent.com/25273387/37255381-16798816-2522-11e8-9066-39b11e4bece0.jpg)

The other shuttlebay also has this problem

macOS 10.12.6 on
2016 MacBook Pro 15" w/ Radeon Pro 4600 4GB & 27" LG 5K monitor.
Core i7 2.9 GHz + 16 GB Ram
V10 QA Release 1

**Comment by dapperrobotbear** [comment] 2018-03-11 22:53
Known issue

**Comment by scragnog** [comment] 2018-03-14 17:08
should be fixed in qa3

**Comment by Sciencekeeper** [comment] 2018-03-17 10:12
@TheStrato can't reproduce anymoe QA4Win

**Comment by TheStrato** [comment] 2018-03-17 10:13
Resolved. Closing ticket.

**Closed by TheStrato** 2018-03-17 10:13 UTC
