### ISSUE TITLE
V0010-QA3 - Data's Quarters surface lighting effect flickering

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#388] opened 2018-03-15 15:21 UTC
**Summary**

The surfaces of multiple meshes flicker continuously as you stand still or move about the room in Data's Quarters.

***What is the expected correct behavior?***

Stable lighting/meshes

**Steps to reproduce**

1.Travel to Data's Quarters
2.Enter and look around the room
3.observe flickering on surfaces, particularly on walls and ceilings

**Relevant logs and/or screenshots**

![mar-14-2018 09-51-42](https://user-images.githubusercontent.com/35311046/37472625-efb3fa9e-2842-11e8-9a4b-c9ec21fca9c8.gif)

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by scragnog** [comment] 2018-03-15 18:13
Unable to replicate on Windows. This must be Mac-specific. @dapperrobotbear are you able to confirm this on your Mac?

**Comment by dapperrobotbear** [comment] 2018-03-15 21:11
This is caused by lighting conflicts between cube maps and dynamic lights.

**Comment by scragnog** [comment] 2018-03-16 19:34
@dapperrobotbear I see, in what way? Any potential solution, or just push this one back?

**Comment by dapperrobotbear** [comment] 2018-03-16 21:27
Turning off "Cast Shadows" on the lights will fix this I believe.

**Comment by dapperrobotbear** [comment] 2018-03-16 21:27
Or removing the offending lights.

**Comment by dapperrobotbear** [comment] 2018-03-18 04:48
Fixed in >QA4

**Comment by EazyCheeze1978** [comment] 2018-03-18 11:44
Looks like it's fixed, here on Windows at least. Not seeing any flickering.

**Comment by TheStrato** [comment] 2018-03-19 04:03
Resolved. Closing this ticket.

**Closed by TheStrato** 2018-03-19 04:03 UTC
