### ISSUE TITLE
Win - V0010-QA1 - Deck 12 Holodeck All Enterprise D Bridges while at Drydock

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#252] opened 2018-03-11 20:53 UTC
**Summary**

When at the Earth Drydock and in the Holodeck in one of the Enterprise D bridges, the view of the Drydock is from above. Not the same view as the Main Bridge.

***What is the expected correct behavior?***

See the same view as Main Bridge, or another simulated view

**Steps to reproduce**

1. Warp to Earth
2. Go to Holodeck
3. Load an Enterprise D Bridge simulation
4.. Look at viewscreen

**Relevant logs and/or screenshots**

![20180311164816_1](https://user-images.githubusercontent.com/4651111/37258335-b0a258b2-254c-11e8-84df-79d920fd555c.jpg)

**Possible fixes**

**Comment by HPringles** [comment] 2018-03-11 21:01
# Confirmed Issue

***Further Testing***

The angle is different from each of the holodecks. 

This is fairly obviously due to the way the holodecks work, teleporting to a different map position

**Comment by dapperrobotbear** [comment] 2018-03-11 22:42
We should probably place the holodecks somewhere else. :-/ or within the ship geometry or something. And the view screen should be the same view as the main bridge's screen. Or something completely different.

**Comment by nkjellman** [comment] 2018-03-12 05:33
Personally, I think the holodeck view should be different than the real view. After all, we want to separate it from reality.

-The TOS bridge would have a Mars like planet at the bottom of the view screen (this was the view in Relics. (You could have this scene in an array of other randomly selected scenes from TOS, like Deep Space K7 from Trouble with Tribbles, the Doomsday Machine planet killer cone thingy, etc...)
-The Season 1 bridge could show the Claw dock like in All Good Things, or it could show the planet that Farpoint Station was on, as homage to the Enterprise's first mission.
-The Yesterday's Enterprise bridge should have the  Enterprise C outside, and the anomaly (This is a detail Guinan would remember from her experience when creating the program).
-The All Good Things bridge could have the anomaly from the episode. (This is a detail Picard would remember from his experience when creating the program).
-The Generations bridge would could show the dry dock, some random planet, or a star background. (The events of Generations haven't been experienced by any of the characters yet. Same thing applies for the Enterprise E bridge when that gets added.)

Drawing separate exterior scenes is something you will have to do for some of the other holodeck programs anyways, like the Forest from Encounter at Farpoint, Dixon Hill, etc...

**Comment by dapperrobotbear** [comment] 2018-03-12 08:59
All good ideas. Probably won't be able to get them in for v10. So just mirroring the current bridge view is what we can do quickly, so it's not some weird view.

**Comment by jeppelykke** [comment] 2018-04-01 17:30
@HPringles Transferred to Bugz

**Closed** 2018-04-01 21:20 UTC
Labels: Enhancement, Windows
