### ISSUE TITLE
Mac - V0010-QA1 - Torpedo Launches from wrong location

### ISSUE THREAD

**Issue by Jaredsfs1** [dapperrobotbear/Stage9#271] opened 2018-03-12 01:51 UTC
**Summary**

When firing the torpedo from the Tactical station, the torpedo launches from somewhere within the Saucer Section, not from the forward Torpedo Launcher in the Stardrive Section.

***What is the expected correct behavior?***

All torpedos fired in the Fore-direction in TNG launch via the forward-facing Main Torpedo Launcher, located above the Main Deflector in the Stardrive Section of the ship.   

**Steps to reproduce**

1.Travel to the Bridge
2.Activate the Tactical console and select the over nacelle view
3.Activate the Tactical console and fire torpedo
4. Observe the sound of the torpedo firing, but the trajectory being blocked in the view screen by the Saucer Section, before the Sensor Array is destroyed by the torpedo.

**Relevant logs and/or screenshots**

![screen shot 2018-03-10 at 11 10 46 pm](https://user-images.githubusercontent.com/35311046/37261921-315dcecc-2576-11e8-83bf-588a60376d34.png)

**Possible fixes**

Spawn the torpedo (sprite?/object?) lower on the Enterprise Model, and closer to the torpedo launcher location before it fires. 

Device:
iMac (Retina 5K, 27-inch, 2017)
3.8 GHz Intel Core i5
24 GB 2400 MHz DDR4
Radeon Pro 580 8 GB

**Comment by jgbr** [comment] 2018-03-12 08:10
Replicated on Mac.

**Comment by jgbr** [comment] 2018-03-12 15:47
also does not fire at Borg cube at all, no graphics at all

**Comment by scragnog** [comment] 2018-03-14 00:25
great catch! Fixed now for next QA release. Torpedoes will now all fire from the fore torpedo launcher

**Comment by Jaredsfs1** [comment] 2018-03-15 18:39
I tried to test in QA3, didn't see a difference,  I'm going to have to try it later with a better machine.

**Comment by Gary-Baggins** [comment] 2018-03-18 14:39
GM1: the torpedo seems to be emanating from the correct place, this would be better confirmed if we could see the Battle Bridge saucer separation view (without separation) before firing a torpedo.

**Comment by TheStrato** [comment] 2018-03-19 04:02
Resolved. Closing this ticket.

**Closed by TheStrato** 2018-03-19 04:02 UTC
