### ISSUE TITLE
Win - V0010-QA1 Detacted head casts shadow

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#185] opened 2018-03-11 01:09 UTC
When in none head bob mode the head casts a shadow. 
![image](https://user-images.githubusercontent.com/5162659/37248377-fa3041aa-249e-11e8-9df4-86d524286aba.png)

**Comment by kaadaq** [comment] 2018-03-11 03:08
Also noticed this when entering Worf's quarters.

**Comment by kaadaq** [comment] 2018-03-11 20:12
I didn't screenshot it, but at one point on the bridge there were TWO head shadows without bodies.  I think one was the tactical officer.  Was standing on the starboard ramp, facing aft engineering station.  As above, 1st person, head bob off

**Comment by HPringles** [comment] 2018-03-14 16:48
# Confirmed Issue

Known Bug

**Comment by MrPeppow** [comment] 2018-03-20 21:53
Can't reproduce anymore. Is fixed? @HPringles @TheStrato

**Comment by HPringles** [comment] 2018-03-20 22:23
@scragnog

**Comment by jeppelykke** [comment] 2018-04-01 21:02
@HPringles transferred to bugz

**Closed** 2018-04-01 21:03 UTC
Labels: Moved Internal
