### ISSUE TITLE
 V0010-QA2 Destination Menu Blocking View

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#345] opened 2018-03-13 20:16 UTC
If you turn on the Warp destination menu. You can sit down and it blocks your view in first person mode. 

What is the expected correct behavior?

When sitting down, the opened Warp Menu should auto close. 

Steps to reproduce

Open up warp menu and sit down.

![image](https://user-images.githubusercontent.com/5162659/37367287-5a2e4318-26d9-11e8-93a0-4f2cb5d63ed5.png)

**Comment by HPringles** [comment] 2018-03-13 20:45
# Confirmed 

Although this is annoying, I'm classing this as an enhancement

**Comment by jgbr** [comment] 2018-03-13 22:18
its exceptionally small that menu in Mac @HPringles

**Comment by JonathanNStewart** [comment] 2018-03-14 04:57
Instead of closing it, personally I'd like to able to select a destination. It seems weird to me to have to stand up to engage warp drive.

**Comment by HPringles** [comment] 2018-03-14 10:03
The Alt Key allows the camera to move and not control the ship. Not a bug - closing.

**Closed by HPringles** 2018-03-14 10:03 UTC
Labels: enhancement
