### ISSUE TITLE
Deck 13 Gab between turbolift and Deck 13

### ISSUE THREAD

**Issue by jeppelykke** [dapperrobotbear/Stage9#110] opened 2017-11-28 14:37 UTC
**PC Spec:** 
Windows 10 Pro (64bit)
Intel Core i7-3770K CPU @ 3.50 GHz, 16 GB RAM, 
Nvidea Geforce GTX 1017 (Version: 388.31)
Screen resolutions: 1920x1080

Game version: Stage9-Windows-v009-QA-Release-2 
**Bug Report:**

Gab between turbolift and Deck 13
![stage9 screenshot 2017 11 28 - 15 35 25 04](https://user-images.githubusercontent.com/33987322/33325247-05aa1490-d452-11e7-8e15-51e82b2aa309.png)

**Comment by Gary-Baggins** [comment] 2018-03-14 12:12
This issue is duplicated in many other tickets, please close @TheStrato @HPringles

**Comment by TheStrato** [comment] 2018-03-14 17:01
Duplicate of other tickets. Closing this ticket.

**Closed by TheStrato** 2018-03-14 17:01 UTC
