### ISSUE TITLE
V0010-QA2 Going To Alternate Camera Views And Using 3rd Person Ship

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#303] opened 2018-03-12 22:09 UTC
When Selecting the Nacelle View and Rear view. Two things happen. The ship exterior model loads into the bridge and Saucer Section gets erased.

What is the expected correct behavior?

When exiting from the seat while in 3rd person view. The exterior model unloads. Saucer Module doesn't disappear. Or block the user in getting up from the seat, in till they go back to first person.

Steps to reproduce

For Exterior bridge model issue. Go to Nacelle camera view.
Go into 3rd person. Now exit 3rd person by getting up from the seat. Don't go back to first person view.

For Saucer vanishing issue.
Go to Rear Camera view.
Repeat other steps.

![image](https://user-images.githubusercontent.com/5162659/37312196-72d13be6-2620-11e8-98bf-a5b3f6af10e9.png)

![image](https://user-images.githubusercontent.com/5162659/37311818-1f06be06-261f-11e8-9a71-479b69bf90de.png)

**Comment by Gary-Baggins** [comment] 2018-03-12 22:52
I can only partially reproduce this (the first image) @TheStrato confirmed bug either way.

**Comment by nkjellman** [comment] 2018-03-12 23:14
I can confirm that the exterior bugs haven't been fixed.

**Comment by Jaredsfs1** [comment] 2018-03-13 16:49
Confirmed Mac bug too @TheStrato @HPringles 

1. It looks like the first issue is just a continuation of issue #331 and of the known issue of the ship mesh not spawning unless you have one of the external views set from the tactical station before trying to control the ship at the Conn.. In this case though, when you have reverse view active, the saucer section is not being spawned (perhaps to save on graphical load, or it's mesh getting in the way of the camera position looking back), so that's all you see when you switch to third-person view.

2. Confirmed, as the opposite of the first bug here; should you be in third-person view, and leave the Conn. station, your player gets up, but the ship mesh is still loaded and overlays inside the bridge because it's slightly out of alignment with the interior modeling.  You can't fix this one, since your Player cannot travel through the hull surface to get back into the Con.. You can even emergency transport to no avail...

![screen shot 2018-03-12 at 11 01 58 pm](https://user-images.githubusercontent.com/35311046/37356685-e9dc1f5c-26bc-11e8-8cc3-ac61cd364bdd.png)

**Comment by jeppelykke** [comment] 2018-04-01 16:17
@HPringles Transferred to Bugz

**Closed** 2018-04-01 16:20 UTC
Labels: Moved Internal
