### ISSUE TITLE
Trapped by invisible wall during warp core breach...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#418] opened 2018-03-19 15:58 UTC
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**

When activating a warp core breach, one gets stuck in the control section of main engineering (Geordi's area - before the second set of blast doors)... can't get past the second set of blast doors before they close - in order to escape into the aft(?) section of main engineering (where the table is).  Almost like an invisible wall there.

***What is the expected correct behavior?***

Should be able to move past the second set of blast doors before they close.

**Steps to reproduce**

1.  Go onto main engineering - control area.
2.  Activate a warp core breach.
3.  Try to escape into the aft(?) part of main engineering.  Can't get past second set of blast doors... like an invisible wall there.

**Relevant screenshots**

![screen shot 2018-03-19 at 10 57 06 am](https://user-images.githubusercontent.com/34230416/37606796-5dbb8e7a-2b64-11e8-984b-8f36379db202.jpg)

Thanks!

**Comment by HPringles** [comment] 2018-03-19 16:18
# This is not a bug 

This is currently the intended behaviour.

As there is not currently a way to escape, and if you got into a turbolift the engineering section would despawn and the events would also stop.

This is a planned change, when there will be interaction.

**Comment by TheStrato** [comment] 2018-03-21 13:55
NaB. Closing this ticket.

**Closed by TheStrato** 2018-03-21 13:55 UTC
