### ISSUE TITLE
V0010-QA3 Right Doors look black when viewed from a Distance

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#382] opened 2018-03-15 03:45 UTC
**Summary**

Basically when walking down corridor, looking at the doors, the right door looks black instead of the same color as the left door

***What is the expected correct behavior?***

Orange color door

**Steps to reproduce**

1. Go to any desk
2. Looks at non-Turbolift doors
3.

**Relevant logs and/or screenshots**

![20180314234059_1](https://user-images.githubusercontent.com/4651111/37443318-bb64c306-27e1-11e8-860b-e6398c86bf56.jpg)

**Possible fixes**

**Comment by TheStrato** [comment] 2018-03-15 03:47
Duplicate of #372. Closing this ticket.

**Closed by TheStrato** 2018-03-15 03:47 UTC
