### ISSUE TITLE
V0010-QA2 Holodeck programs unload to open space if going to Sickbay area and back to Holodeck

### ISSUE THREAD

**Issue by trekkeriii** [dapperrobotbear/Stage9#310] opened 2018-03-13 00:52 UTC
**Summary**

If you load a program on the Holodeck, then take the Turbolift to Sickbay and then come back to Holodeck directly, Holodeck door goes to open space, not the typical hologrid room.

***What is the expected correct behavior?***

Program still loaded or the hologrid

**Steps to reproduce**

1. Launch a program in the Holodeck
2. Take Turbo to Sickbay
3. Take Turbo directly back to Holodeck
4. Attempt to enter Holodeck,

**Relevant logs and/or screenshots**

![20180312204126_1](https://user-images.githubusercontent.com/4651111/37316752-46162618-2637-11e8-8c7b-cc78bb621f65.jpg)

(Paste any relevant logs - please use code blocks  to format console output,
logs, and code as it's very hard to read otherwise.)

**Possible fixes**

**Comment by Gary-Baggins** [comment] 2018-03-13 14:31
Confirmed.

**Comment by nkjellman** [comment] 2018-03-17 03:20
@scragnog @TheStrato

I know of a way you can fix this and another two bugs.
-Leave the holodeck room loaded.
-Make the hide arch button also hide the portal on the outside.

The benefits to these two changes.
-You won't see the stars when switching programs.
-When inside the holodeck, the exit door won't be so dark and fake looking.
-Because the holodeck room is still loaded, and the portal going into the program will disappear when you press Q, it will look like you ended the program, thus working around the hide arch outside the holodeck issue.

**Comment by jeppelykke** [comment] 2018-04-01 16:24
@HPringles Transferred to Bugz

**Closed** 2018-04-01 16:25 UTC
Labels: Moved Internal
