### ISSUE TITLE
V0010 - Bridge - Red alert to yellow alert does not fully deactivate (red alert)...

### ISSUE THREAD

**Issue by tenko23** [dapperrobotbear/Stage9#417] opened 2018-03-19 15:47 UTC
**Basic Info**

Discord Name(If Applicable):  tenko23
CPU:  2 x 3.46 GHz 6-Core Intel Xeon
GPU:  AMD Radeon HD 7950 3 GB graphics
Operating System:   MacOS 10.3.3

**Summary**

When going from red alert to yellow alert on the bridge, the yellow alert lights light up on the LCARS panels, but the red alert lights keep flashing around the bridge.

***What is the expected correct behavior?***

The red alert lights should stop flashing

**Steps to reproduce**

1.  Go onto bridge.
2.  Turn on red alert using the menu.
3.  Go to yellow alert using the menu.  Red alert lights do not deactivate.

**Relevant screenshots**

![screen shot 2018-03-19 at 10 44 27 am](https://user-images.githubusercontent.com/34230416/37606026-8a28c2ea-2b62-11e8-8ea6-c815e1963853.jpg)

Thanks!

**Comment by jgbr** [comment] 2018-03-19 16:27
Confirmed bug exits and is also Multiplatform [Mac] from a tester

**Comment by HPringles** [comment] 2018-03-19 16:31
@scragnog Is this intended?

**Comment by jgbr** [comment] 2018-03-19 16:51
Canon confirmation that yellow alert, does not start red alert flashing. Season 3 E2.

![ya](https://user-images.githubusercontent.com/37260734/37609701-b66edab4-2b95-11e8-8703-5aed392b771e.jpeg)

**Comment by tenko23** [comment] 2018-03-20 23:36
It only happens when going from red alert to yellow alert.  Going from "no alert" to yellow alert (and then red alert) works correctly.

**Comment by jgbr** [comment] 2018-03-22 08:45
I rewatched a few episodes and when yellow alert is activated, the computer on other decks states : "All decks, Yellow Alert'.

**Comment by tenko23** [comment] 2018-03-22 08:47
I do remember at least one :) !  I think there was one that announced a red alert (in one episode), too ;o ~

**Comment by OssiBRI** [comment] 2018-03-22 15:10
There's a sound that's played when yellow alert is turned on. It's actually in Stage 9, already. In the Borg sequence, after the computer announces "tactical alert, blablabla".

**Comment by tenko23** [comment] 2018-03-22 17:08
When watching the series... usually that sound is only heard on the bridge (if I remember right).  Do you remember which episodes those were when you heard that announcement, @jgbr ;o ???  The one I was thinking of where the computer announces red alert was from s4 ep12 - "The Wounded"... timestamp 2:57.  The computer announces with the emergency tone:  "Red Alert, take emergency stations."

![screen shot 2018-03-22 at 12 01 00 pm](https://user-images.githubusercontent.com/34230416/37785784-089698ba-2dc9-11e8-9007-38fc86e99e99.jpg)

I watched "Encounter at Farpoint" - the first TNG episode, when it was premiered (aired) for the first time on CBS back in 1980-whatever it was... only missed one episode throughout the whole TNG run, as the aired.  Since that first episode (and before, with the movies & TOS), I've lived and breathed Star Trek ;p .  Been there, done that - pretty much seen them all, too xD heheh ;p ~

**Comment by tenko23** [comment] 2018-03-23 07:54
I managed to get a sound recording of that clip ;D .....
(zipped, due to m4a's not being allowed ;o ~)

[alert.m4a.zip](https://github.com/dapperrobotbear/Stage9/files/1840585/alert.m4a.zip)

**Comment by jeppelykke** [comment] 2018-04-01 14:51
@HPringles Transferred to Bugz

**Closed** 2018-04-01 21:19 UTC
Labels: Bug, Linux, Mac, Moved Internal, Windows
