### ISSUE TITLE
Win - V0010-QA1 Deck 2 Lighting

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#190] opened 2018-03-11 01:33 UTC
Coming out of the Deck 2 Port Crew Quarters Turbolift. All of Deck 2's lighting is too dark.

![image](https://user-images.githubusercontent.com/5162659/37248511-3fa24528-24a2-11e8-83f9-e323425c3838.png)

**Comment by Sciencekeeper** [comment] 2018-03-11 09:23
Confirmed seems to be a problem with the Cube Map

**Comment by HPringles** [comment] 2018-03-11 20:26
# Confirmed Issue

**Comment by MrPeppow** [comment] 2018-03-14 12:41
Can confirm, happens on Linux QA1 on Deck 2, 6, 7, 9, 10, 12 and 13

**Comment by scragnog** [comment] 2018-03-18 12:37
lowering cubemap intensity made these corridors darker. added some pointlights in, problem solved!

**Comment by jeppelykke** [comment] 2018-03-18 12:48
Confirmed fixed for: Win - V0010-GM1

**Comment by TheStrato** [comment] 2018-03-19 04:01
Resolved. Closing this ticket.

**Closed by TheStrato** 2018-03-19 04:01 UTC
