### ISSUE TITLE
Win - V0010-QA1 TOS Bridge Viewscreen

### ISSUE THREAD

**Issue by archer9234** [dapperrobotbear/Stage9#197] opened 2018-03-11 02:05 UTC
Blank only displaying white.

![image](https://user-images.githubusercontent.com/5162659/37248692-b8052630-24a6-11e8-8c61-2842b8ed7d1d.png)

**Comment by HPringles** [comment] 2018-03-11 19:05
# Confirmed Issue

***Seems to be related to the stellar cartography issue #193 ***

**Comment by Gary-Baggins** [comment] 2018-03-11 20:38
Confirmed.

**Comment by jeppelykke** [comment] 2018-04-01 21:48
@HPringles Transferred to Bugz

**Comment by tenko23** [comment] 2018-04-02 04:44
@TheStrato

**Closed** 2018-04-02 08:52 UTC
Labels: Moved Internal
