### ISSUE TITLE
V0010-QA1 - open wall at deck 3

### ISSUE THREAD

**Issue by www2000** [dapperrobotbear/Stage9#359] opened 2018-03-14 11:53 UTC
**Summary**

Open wall at deck 3

***What is the expected correct behavior?***

A solid wall.

**Steps to reproduce**
1. Go to Turbolift destination Shuttle bay 1 Office | Port Bow
2. exit the Turbolift go right en walk to the end to the corridor
3. the hole is on the left side

**Relevant logs and/or screenshots**

https://imgur.com/a/xYCma

**Possible fixes**

Block the wall.

**Comment by JonathanNStewart** [comment] 2018-03-14 14:18
Duplicate of #237 (although for Linux).

**Comment by scragnog** [comment] 2018-03-14 14:47
@dapperrobotbear did you already fix this? I'm seeing the wall in there now.

**Comment by kaadaq** [comment] 2018-03-15 02:03
Bulkheads Verified as fixed in QA3.  However....

Outside of the control room (03:2595) there's now a whole side wall missing.
![image](https://user-images.githubusercontent.com/34050343/37440542-7aaa2b48-27d3-11e8-897a-2fc2f8f98846.png)

**Comment by TheStrato** [comment] 2018-03-15 02:07
Original issue repaired, new area new original issue found buggy. Placing back in pipeline.

**Comment by dapperrobotbear** [comment] 2018-03-15 11:12
Fixed in QA4. Technically this is a dupe now.

**Comment by TheStrato** [comment] 2018-03-17 09:32
Resolved. Closing ticket.

**Closed by TheStrato** 2018-03-17 09:32 UTC
